# Generated by Django 2.1.7 on 2019-04-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='item',
        ),
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
